# Generated by Django 4.0.1 on 2022-02-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_task_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='suspend_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='total_suspend_time',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
